/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aryoovpidvpbuyyiyseu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeW9vdnBpZHZwYnV5eWl5c2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjY0NzQsImV4cCI6MjA3NjIwMjQ3NH0.dHnWV5V39TSaZmh4tsIH8ljrEs5iJ7JhlQeH1WY8bQw"
export const apiBaseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-ebae10ad`